from enum import Enum

class Salle(Enum) :
        SALLE_ADA = "CERI_ADA"
        SALLE_BLAISE = "CERI_BLAISE"
        SALLE_CISCO = "CERI_CISCO"
        SALLE_ELEC = "CERI_ELEC"
        SALLE_RES = "CERI_RES"
        SALLE_ROB = "CERI_ROB"
        SALLE_S1 = "CERI_S1"
        SALLE_S2 = "CERI_S2"
        SALLE_S3 = "CERI_S3"
        SALLE_S4 = "CERI_S4"
        SALLE_S5 = "CERI_S5"
        SALLE_S6 = "CERI_S6"
        SALLE_S7 = "CERI_S7"
        SALLE_S8 = "CERI_S8"
        SALLE_STAT1 = "CERI_STAT1"
        SALLE_STAT2 = "CERI_STAT2"
        SALLE_STAT3 = "CERI_STAT3"
        SALLE_STAT4 = "CERI_STAT4"
        SALLE_STAT5 = "CERI_STAT5"
        SALLE_STAT6 = "CERI_STAT6"
        SALLE_STAT7 = "CERI_STAT7"
        SALLE_STAT8 = "CERI_STAT8"
        SALLE_STAT9 = "CERI_STAT9"